[DPRMemSAM]
label = DPRMemSAM
protocol = traxpython
command = vot_wrapper_DPRMemSAM
paths = ../../../methods/DPRMemSAM
env_PATH = ${PATH}
env_DAM4SAM_MODEL = sam21pp-L
timeout = 600

# Sanity Check
[NCCPython]  # Test Tracker to check that everything runs
label = PyNCC
protocol = traxpython
command = ncc_singleobject_mask
# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
paths = ../../vot_ncc_test_integration/python
# Additional environment paths
env_PATH = ${PATH}
timeout = 600